Algoritmo "celsius_fahrenheint"
// Disciplina   : [Lógica de Programação com Javascript]
// Professor   : Jailson Costa
// Descrição   : Traduz graus fahrenheint em celsius
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 18/03/2024
Var
fahren: real
grauscelsius: real


Inicio
Escreval("Digite o valor dos graus Fahrenheint")
Leia(fahren)
grauscelsius<- 5 *(fahren - 32)/9
Escreval(fahren," em Celsius é ", grauscelsius)


Fimalgoritmo