Algoritmo "impar_par"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Determina se o valor digitado é ímpar ou par
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 25/03/2024
Var
num: inteiro


Inicio
Escreval("Digite um valor ímpar ou par")
leia(num)
se (num mod 2 =0) então
Escreval("Este número é par")
senão
Escreval("Este número é ímpar")
Fimse

Fimalgoritmo