Algoritmo "L03b"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar a soma obtida dos cem primeiros números inteiros
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 01/05/2024
Var
numero,soma: inteiro

Inicio
numero<- 1
enquanto numero <= 100 faca
soma<- soma + numero
escreval(soma)
numero<- numero + 1
fimenquanto
fimalgoritmo