Algoritmo "L03d"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar os valores ímpares de 0 a 20
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 01/05/2024
Var
numero: inteiro

Inicio
enquanto numero <= 20 faca
se numero mod 2 <> 0 entao
escreval(numero)
fimse
numero<- numero + 1
fimenquanto
fimalgoritmo