Algoritmo "L03e"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Apresentar as potências de 3 com expoentes de 0 a 15
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 01/05/2024
Var
expoente,valor: real

Inicio

enquanto expoente <= 15 faca
valor<- 3 ^ expoente
escreval("3 elevado a",expoente," é",valor)
expoente<- expoente + 1
fimenquanto
fimalgoritmo