Algoritmo "verificacao_numero"
// Disciplina   : [Lógica de Programação com JavaScript]
// Professor   : Jailson Costa dos Santos
// Descrição   : Só valida números menores ou iguais a 3
// Autor(a)    : Maria Eduarda de Sales Miranda
// Data atual  : 25/03/2024
Var
num: inteiro


Inicio
Escreval("Digite um valor inteiro")
leia(num)
se (num <= 3) então
Escreval("Este número é: ",num)
senão
Escreval("Este número não é válido")
Fimse

Fimalgoritmo